version: "3.7"
services:
  mlflow:
      container_name: mlflow
      build:
        context: .
        dockerfile: Dockerfile
      image: abtest-mlops_mlflow
      ports:
        - "5000:5000"

      