stages:
  cleaing:
    cmd: python scripts/clean.py data/store.csv
    deps:
    - data/store.csv
    - scripts/clean.py
    outs:
    - data/clean.csv
  eda:
    cmd: python scripts/eda.py data/clean.csv
    deps:
    - data/clean.csv
    - scripts/eda.py
    outs:
    - data/eda.csv
