stages:
  prepare:
    cmd: cd scripts && python clean.py ${dataset.no_observations}
    deps:
    - data/amharic_train_text.txt
    - data/amharic_train_wav/
    - data/swahili_train_text.txt
    - data/swahili_train_wav/
    params:
    - dataset.no_observations
    outs:
    - data/amharic.csv
    - data/swahili.csv
  train:
    cmd: cd scripts && python deep_learner.py ${model.epochs} ${model.learning_rate}
    deps:
    - data/amharic.csv
    - data/swahili.csv
    - scripts/deep_learner.py
    params:
    - model.epochs
    - model.learning_rate
    outs:
    - models/model.pkl
  