stages:
  prepare:
    cmd: python scripts/eda.py data/AdSmartABdata.csv
    deps:
    - data/AdSmartABdata.csv
    - scripts/eda.py
    
  abtest:
    cmd: python scripts/abtest.py data/AdSmartABdata.csv data/abtest
    deps:
    - data/AdSmartABdata.csv
    - scripts/abtest.py
    
  sequentialAbtesting:
    cmd: python scripts/sequential.py data/abtest data/sequential
    deps:
    - data/abtest
    - scripts/sequential.py
  
  train:
    cmd: python scripts/modeling.py data/sequential data/train
    deps:
    - data/sequential
    - scripts/modeling.py
    
  model:
    cmd: python scripts/modeling.py data/train data/model
    deps:
    - data/train
    - scripts/modeling.py
  
  evaluate:
    cmd: python scripts/modeling.py data/model data/evaluate
    deps:
    - data/model
    - scripts/modeling.py