stages:
  # first stage in the pipeline
  prepare:
    cmd: python scripts/eda.py data/AdSmartABdata.csv
    deps:
    - data/AdSmartABdata.csv
    - scripts/eda.py
    outs:
    - data/eda.csv
  train:
    cmd: cd pipeline && python pipeline/train.py data/eda.csv
    deps:
    - data/eda.csv
    - pipeline/train.py
    outs:
    - data/train.csv
  crossValidation:
    cmd: cd pipeline && python pipeline/cross_validator.py data/train.csv
    params:
    - '5' 
    deps:
    - data/train.csv
    - pipeline/cross_validator.py
    outs:
    - data/validation.csv
  evaluate:
    cmd: cd pipeline && python pipeline/evaluate.py data/validation.csv
    params:
    - '5'
    deps:
    - data/validation.csv
    - pipeline/evaluate.py
    outs:
    - data/results.csv
