stages:
  prepare:
    cmd: python scripts/eda.py data/AdSmartABdata.csv
    deps:
    - data/AdSmartABdata.csv
    - scripts/eda.py
    outs:
    - data/prepare
  abtest:
    cmd: python scripts/abtest.py data/prepare
    deps:
    - data/prepare
    - scripts/abtest.py
    outs:
    - data/abtest
  sequentialAbtesting:
    cmd: python scripts/sequential.py data/abtest
    deps:
    - data/abtest
    - scripts/sequential.py
    outs:
    - data/sequential
  train:
    cmd: python scripts/modeling.py data/sequential
    deps:
    - data/sequential
    - scripts/modeling.py
    outs:
    - data/train
  crossValidation:
    cmd: python scripts/modeling.py data/train
    deps:
    - data/train
    - scripts/modeling.py
    outs:
    - data/crossValidation
  evaluation:
    cmd: python scripts/modeling.py data/crossValidation
    deps:
    - data/crossValidation
    - scripts/modeling.py
    outs:
    - data/evaluation
