stages:
  prepare:
    cmd: python clean.py
    deps:
    - data/amharic_train_text.txt
    - data/amharic_train_wav/
    - data/swahili_train_text.txt
    - data/swahili_train_wav/
    outs:
    - amharic.csv
    - swahili.csv
