name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              No they are not similar, we see that there is differences in:

              day of week-slight difference in 4-5 in test set
              school holiday - difference in number of ones in test set
              promo 2 since week - has lower values in between the peaks in the test set
              promo 2 since year - has slight difference in year 2013 and 2014
              day - has lower days towards the end in the test set
              month - has no values in between the peaks in the test set
              year - centered only on one peak that is 2015
              day of year - has lower values towards the end in the train set
              week of year - has downward trend in the training set, while in the test set it tries to be consistent
              no customers and sales columns in test set


          " > report.md
          cml send-comment report.md