name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              We can notice that before the holidays the sales that is when school holidays = 0, the sales are more but when there are school holidays, that is when holidays = 1, we notice that there is a decrease in the sales
              We can note that when there are no state holidays, that is when stateholiday = 0, there are more sales, and then we notice that during the state holidays, there are fewer sales,
          " > report.md
          cml send-comment report.md