name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              What we can see is that stores that have assortment a are the ones with the highest sales, 
              pretty much, and then it is followed with stores with assortment c, 
              but stores with assortment b seem to be really low on sales
          " > report.md
          cml send-comment report.md