name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              Noting that in the graph, we have a = public holiday, b = Easter holiday, c = Christmas, 0 = None, we notice that
              most of the sales are done when stateholiday=0, but we notice that there is a strong decrease during the holidays,
              that is very few sales are done during the public holidays,easter and christmas, However we can note that
              in the easters there are more sales in the public holidays, than in the easter and christmas holidays, 
              and that there are more sales in the easter holidays, than in the christmas holidays
          " > report.md
          cml send-comment report.md