name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              We notice that there is a high correlation between the customers, and the sales
              and the relationship is a positive/direct type of relationship that is as the customers grow
              likewise do the sales, but customers column/feature is not in the test set, therefore we can only use it in 
              some analysis but not all
          " > report.md
          cml send-comment report.md