name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              Opening affects stores, in this sense. It begins with a low and then it picks up very 
              slowly because as you can see in the line graph, it takes quite some time before reaching 
              the peak. But it does have some peaks, though they are not so frequent. I want to believe 
              that it is because the clientele is formed from scratch, and it takes time to win their 
              confidence. What I would recommend is that if there is any opening to take place, 
              let it be done in a thriving atmosphere. I shall look more keenly into store 291, 
              to see why this one has abnormally picked like crazy.
          " > report.md
          cml send-comment report.md