name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              A huge percentage of the stores open on all weekdays, and close on weekends, 
              this could probably be because many customers are not available during the weekend, 
              also it could be that the store workers have closed for some rest. 
              And we notice that there are some peak days like day 2 and 6.
          " > report.md
          cml send-comment report.md