name: sales_predictions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "
              Yes we see that for promos below 10000, there is no 
              impact on the side of the stores, but for promos above 10,000 there is significant 
              change in such stores, I would recomend that promos to be deployed in stores that are 
              between the 15,000 - 20000 mark, that is the following stores
              -       [3,   11,   17,   24,   27,   28,   35,   52,   54,   58,   71,
                      77,   82,  102,  120,  126,  137,  140,  146,  153,  156,  162,
                      164,  166,  169,  181,  192,  199,  213,  214,  223,  229,  247,
                      248,  256,  261,  272,  303,  308,  319,  323,  344,  368,  370,
                      371,  372,  375,  377,  380,  381,  386,  391,  400,  401,  421,
                      427,  434,  449,  450,  459,  479,  489,  492,  502,  503,  506,
                      507,  518,  522,  534,  536,  539,  544,  545,  552,  571,  572,
                      575,  587,  603,  605,  608,  612,  613,  616,  623,  629,  636,
                      641,  643,  644,  655,  657,  665,  674,  677,  685,  695,  705,
                      708,  711,  720,  721,  739,  745,  753,  754,  759,  765,  775,
                      784,  792,  815,  822,  835,  846,  848,  862,  868,  869,  872,
                      876,  897,  914,  926,  947,  954,  967,  971,  974,  983,  985,
                      986,  993,  996,  999, 1003, 1010, 1011, 1019, 1023, 1026, 1027,
                      1032, 1039, 1040, 1048, 1050, 1051, 1086, 1092, 1099, 1107]
          " > report.md
          cml send-comment report.md